# This workflow automates the release process: when a branch matching "release/vX.Y.Z" is merged
# into "main", automatically create a new **draft** release with information about the release with
# a production-ready "plugin-starter.zip" release asset.
name: Release

# Only execute when a release branch has been merged into "main".
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:

  # Automatically prepare a release following a successful merge into "main".
  prepare-release:
    if: github.event.pull_request.merged == true
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine the release version
        id: parse-version
        env:
          # This looks scary, but it's a PCRE regular expression that parses the version number
          # from a branch name based on semver.
          #
          # Reference and examples of matched patterns: https://regexr.com/6jfqu
          pattern: '(?:^|\/)v?\.?\K(\d+\.\d+\.\d+(-[0-9A-Za-z-]+(?:\.\d+)?)?(\+(?:\.?[0-9A-Za-z-]+)+)?)$'
        run: |
          version=$(grep -oP "${{ env.pattern }}" <<< "${{ github.event.pull_request.head.ref }}")
          echo "::set-output name=version::$version"
          echo "Parsed version: '${version}'"

      - name: Configure PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          coverage: none

      - name: Configure Composer
        run: composer config github-oauth.github.com ${{ secrets.STELLARWP_ACCESS_TOKEN }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --no-dev --optimize-autoloader

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Build the release archive
        run: ./bin/build

      - name: Publish the draft release
        id: publish
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.parse-version.outputs.version }}"
          commit: main
          name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: true
          prerelease: ${{ contains(steps.parse-version.outputs.version, '-') }}
          artifacts: plugin-starter.zip
          artifactErrorsFailBuild: true

      - name: Release details
        run: |
          echo "Draft release has been published: ${{ steps.publish.outputs.html_url }}"
